Merge pull request #3 from kubeservice-stack/main
kubeservice-stack/basa pull request #4
Opened 2022-12-01 07:31 UTC by dongjiang1989

Update bugFix

2022-12-14 02:42 UTC, imlense requested changes

2022-12-14 02:42 UTC, imlense commented on src/backend/controllers/kubernetes/node/terminal.go
> +	case "resize":
Add reset model

2022-12-14 02:42 UTC, imlense commented on src/backend/controllers/kubernetes/node/terminal.go
> +	pod := c.Ctx.Input.Param(":pod")
node 部署 特殊Pod（PIC、PID、HostNetwork共享host），pod名称uuid随机产生。不需要container name传递

2022-12-14 02:42 UTC, imlense commented on src/backend/controllers/kubernetes/node/terminal.go
> +	pod := c.Ctx.Input.Param(":pod")
node 部署 特殊Pod（PIC、PID、HostNetwork共享host），pod名称uuid随机产生。不需要container name传递

2022-12-15 04:55 UTC, dongjiang1989 commented on src/backend/controllers/kubernetes/node/terminal.go
> +	pod := c.Ctx.Input.Param(":pod")
done 
添加在pod层面默认启动一个Pod

2022-12-16 01:51 UTC, dongjiang1989 commented
Add Pod Create, Delete, Get method, when Node want to webshell terminal to Node, Frist Create Pod, than web socket

2022-12-23 07:15 UTC, merged